# Generated by Django 2.0.3 on 2018-03-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wybor_tekst', models.CharField(max_length=200)),
                ('glosy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie_tekst', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='data publikacji')),
            ],
        ),
        migrations.AddField(
            model_name='odpowiedz',
            name='pytanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankieta.Pytanie'),
        ),
    ]
